server:
  port: 8097


mybatis:
  type-aliases-package: com.ustcinfo.hftnews.model
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com.ustcinfo.wa.dao: debug
  config: classpath:log4j2.xml

spring:
  datasource:
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10